In [47]:
import numpy as np
import pandas as pd

Pandas Series

In [48]:
# a series is a 1D array and capable to hold diff datatypes , the axies labels are collectively called the index

In [49]:
labels =["a","b","c"]
my_list =[10,20,30]
arr = np.array([10,20,30])
d= {1:10,2:20, 3:30}

In [50]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [51]:
pd.Series(my_list,index =labels)

a    10
b    20
c    30
dtype: int64

In [52]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [53]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

DATAFRAME

In [54]:
import numpy as np
import pandas as pd

In [55]:
# CREATING A DATAFRAME

In [56]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df= pd.DataFrame(data)

In [57]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [58]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2= pd.DataFrame(data_list)
columns = ["Name", "Age", "City","Salary"]
df3= pd.DataFrame(data_list ,columns=columns)

In [59]:
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [60]:
df3

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [61]:
# selection and indesing of columns

In [62]:
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [63]:
df3["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [64]:
df3[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [65]:
# creating a new columns

In [66]:
df3["Designation"]=["Doctor","Engineer","Docter","Engineer"]

In [67]:
df3

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Docter
3  Linda   42    London   85000    Engineer

In [68]:
# removing columns

In [69]:
df3.drop("Designation",axis=1, inplace = True)
# vertical is axis 1 and horizontal is axis 0

In [69]:
# inplace is used to parmenataly selection of colume ,otherwise it just create a copy of it

In [70]:
df3

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [71]:
# selecting rows

In [74]:
df2.loc[0]
# loc is a location

0        John
1          28
2    New York
3       65000
Name: 0, dtype: object

In [75]:
df2.loc[[0,1]]

      0   1         2      3
0  John  28  New York  65000
1  Anna  34     Paris  70000

In [77]:
df.iloc[3]
# iloc is a location of index

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [72]:
# selecting subsets of rowa and columns

In [78]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [73]:
# conditional selection

In [79]:
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000