<a href="https://colab.research.google.com/github/tanviengineer/ai-learning-journey/blob/main/python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# variable
name = "tanvi"
course = " msc Artificial Intelligence "
roll_no = 23
print(name)
print(course)
print(roll_no)
print("My name is ",name,". I am student of ",course,". My roll no is ",roll_no,"," )

tanvi
 msc Artificial Intelligence
23
My name is  tanvi . I am student of   msc Artificial Intelligence  . My roll no is  23 ,

In [ ]:
# data types

# integer
roll_no = 23
# float
height = 5.4
# string
name = "Tanvi"
# boolen
passed = True
failed = False

print(type(roll_no))
print(type(height))
print(type(name))
print(type(passed))
print(type(failed))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
<class 'bool'>

In [ ]:
# input and output
name = input( "what is your name  ")
# print(name)
age  = int(input ("Enter your age : "))
# print(age)
salary= float(input("Enter your salary : "))
# print(salary)
print("Hello ",name,", You are age is",age,". Yours salary is ",salary)

what is your name  Tanvi
Enter your age : 20
Enter your salary : 50000
Hello  Tanvi , You are age is 20 . Yours salary is  50000.0

In [ ]:
# operators
a= 10
b= 20

print("Airtmetic operator")
# add
print(a+b)
# sub
print(a-b)
# mul
print(a*b)
# div
print(a/b)
# mod
print(a%b)
# power
print(a**b)

print("comparision operator")
print(5<5)
print(5<6)
print(5==4)
print(5!=4)
print(5<=5)

print("Logical Operators")
print(True or False)
print(True and False)
print(not True )

Airtmetic operator
30
-10
200
0.5
10
100000000000000000000
comparision operator
False
True
False
True
True
Logical Operators
True
False
False

In [ ]:
# TYPE casting

#  string to int
a ="10"
b=int(a)
print(type(b))

# int to str
a = 10
b= str(a)
print(type(b))

# int to float
a= 23
b = float(a)
print(b)

# float to int
a =10.5
b = int(a)
print(b)

# practice
num1 = input("Enter  a number :")
num2 = float(num1)
print(num2 + 20)

<class 'int'>
<class 'str'>
23.0
10
Enter  a number :78
98.0

In [ ]:
# practice
a = float(input("Enter the Length : "))
b = float(input("Enter the Breadth : "))
area = a*b
print(area)

Enter the Length : 4
Enter the Breadth : 3
12.0

In [ ]:
# practice
c = float(input("Enter the temperature in celsius"))
f = (c* 9/5)+32
print("Temperature in fehrenheit",f)

Enter the temperature in celsius11
Temperature in fehrenheit 51.8

LIST

In [ ]:
fruits = [1,2,3,5,6,7,8,90,9,5,3,4,5]
print(fruits)

[1, 2, 3, 5, 6, 7, 8, 90, 9, 5, 3, 4, 5]

In [ ]:
# indexing
print(fruits[0])
print(fruits[2])
print(fruits[-4])

1
3
5

In [ ]:
# slicing
print(fruits[1:6])
print(fruits[4:7])

[2, 3, 5, 6, 7]
[6, 7, 8]

In [ ]:
# methods ()

# append()
fruits.append(1000)
print(fruits)
# remove()
fruits.remove(1)
print(fruits)
# sort()
fruits.sort()
print(fruits)
# decending sort()
fruits.sort(reverse= True)
print(fruits)

# lengh()
print(len(fruits))
# max()
print(max(fruits))
# min()
print(min(fruits))
# sum()
print(sum(fruits))

[1, 2, 3, 5, 6, 7, 8, 90, 9, 5, 3, 4, 5, 1000]
[2, 3, 5, 6, 7, 8, 90, 9, 5, 3, 4, 5, 1000]
[2, 3, 3, 4, 5, 5, 5, 6, 7, 8, 9, 90, 1000]
[1000, 90, 9, 8, 7, 6, 5, 5, 5, 4, 3, 3, 2]
13
1000
2
1147

In [ ]:
# practice  ---find average
avg =sum(fruits)/len(fruits)
print(avg)

88.23076923076923

TUPLE

In [ ]:
# tuple never change
# use when data is fixed-used for image dimensions
colors= ("red","blue","green")
print(colors)
rbg =("255",'255','255')
print(rbg)

('red', 'blue', 'green')
('255', '255', '255')

DICTIONARY

In [ ]:
student ={
    "name":"Tanvi",
    "age":20,
    "city":"Shimla"
}
print(student)

{'name': 'Tanvi', 'age': 20, 'city': 'Shimla'}

In [ ]:
# acces
print(student["name"])

Tanvi

In [ ]:
print(student["age"])

20

In [ ]:
print(student["city"])

Shimla

In [ ]:
# update
student["city"]= "kangra"
print(student["city"])

kangra

In [ ]:
# add
student["roll no"]=23
print(student.keys())

dict_keys(['name', 'age', 'city', 'roll no'])

In [ ]:
print(student.values())

dict_values(['Tanvi', 20, 'kangra', 23])

In [ ]:
print(student.items())

dict_items([('name', 'Tanvi'), ('age', 20), ('city', 'kangra'), ('roll no', 23)])

In [ ]:
print(student)

{'name': 'Tanvi', 'age': 20, 'city': 'kangra', 'roll no': 23}

In [ ]:
for keys ,values in student.items():
  print(keys,values)

name Tanvi
age 20
city kangra
roll no 23

SET

In [ ]:
# set is used for duplicate values
# useful for ml to remove the duplicate values
# useful when we have a user id
no ={1,2,2,3,3,4,4,5,6,7,7,5,5,5,6,3}
print(no)

{1, 2, 3, 4, 5, 6, 7}

In [ ]:
# practice--convert into set
num = [1,2,3,4,4,56,8,9,0,5,4,6,43,35]
num2 = set(num)
print(num2)

{0, 1, 2, 3, 4, 5, 6, 35, 8, 9, 43, 56}

In [ ]:
num3 =list(set(no))
print(num3)

[1, 2, 3, 4, 5, 6, 7]

In [ ]:
# practice
marks = [55,76,43,78,97,55,46,96,56,35,87,84,46,99]
print(max(marks))
print(min(marks))
print(sum(marks)/len(marks))
# Sorts the list in-place, returns None. Print marks after sorting to see the effect.
marks.sort()
print(marks)

print("Marks greater than 80:")
for mark in marks:
  if mark > 80:
    print(mark)

99
35
68.07142857142857
[35, 43, 46, 46, 55, 55, 56, 76, 78, 84, 87, 96, 97, 99]
Marks greater than 80:
84
87
96
97
99

if , elif , else

In [ ]:
age = 20
if age<20:
  print("adult")
else:
  print("minor")

minor

In [ ]:
day = 1
if day ==2:
  print("monday")
elif day== 1:
  print("tuesday")
elif day ==3:
  print("wednesday")
else:
  print("enter valid data")

tuesday

FOR LOOP

In [ ]:
# used for repetation for work
for i in range(5):
  print(i)

0
1
2
3
4

In [ ]:
for i in range(5):
  print("Hello TANVI")

Hello TANVI
Hello TANVI
Hello TANVI
Hello TANVI
Hello TANVI

In [ ]:
fruits =["graphs",'apple','banana','mango','kiwi']
for i in fruits:
  print(i)

graphs
apple
banana
mango
kiwi

In [ ]:
for i in range (1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10

In [ ]:
for i in range(3,30,3):
  print(i)

3
6
9
12
15
18
21
24
27

WHILE LOOP

In [ ]:
# while loop run until condition is true

In [ ]:
i = 1
while i<=5:
  print(i)
  i+=1

1
2
3
4
5

In [ ]:
i=1
while i<=5:
  print(i)
  i=i+2

1
3
5

In [ ]:
password =""
while password != "python":
  password = input("Enter the pasword :")
  if password =="pyhton":
    print("corrrect password")
  else:
    print("enter a wrong password")

Enter the pasword :ffff
enter a wrong password
Enter the pasword :fddws
enter a wrong password
Enter the pasword :python
enter a wrong password

In [ ]:
# practice
password =input("")
while password !="python":
  password =input("enter a valid pasword ")
  if password =="python":
    print("welcome ,you")
  else:
    print("you enter a wrong password")

sss
enter a valid pasword tdcs
you enter a wrong password
enter a valid pasword sas
you enter a wrong password
enter a valid pasword python
welcome ,you

In [ ]:
# break
for i in range (0,100,5):
  if i== 50:
    break
  print(i)

0
5
10
15
20
25
30
35
40
45

In [ ]:
# coutinue
for i in range (0,11):

  if i==5:
    continue
  print(i)

0
1
2
3
4
6
7
8
9
10

FUNCTION

In [ ]:
def welcome():
  print("hello ,tanvi")

In [ ]:
welcome()
welcome()
welcome()

hello ,tanvi
hello ,tanvi
hello ,tanvi

In [ ]:
# parameter
def greet(name):
  print("hello",name)

In [ ]:
greet("tanvi")
greet("lakshay")
greet("deepika")

hello tanvi
hello lakshay
hello deepika

In [ ]:
def greet(name):
  return "hello "+ name

In [ ]:
# practice
name =str(input("Enter your name  : "))
password =input("Enter password : ")
while password !="python":
  password =input("enter a valid pasword ")
  if password =="python":
    print(greet(name))
  else:
    print("you enter a wrong password")

Enter your name  : tanvi
Enter password : hdsj
enter a valid pasword python
hello tanvi

In [ ]:
# multiple parameter
def add(a,b):
  print(a+b)

In [ ]:
result1 =add(200,222)
result1
result2 =add(22,424)
result2

422
446

In [ ]:
# return
def sub(c,d):
  return c-d

In [ ]:
result =sub(12,34)
result

-22

In [ ]:
def mul(a,b):
  print(a*b)

In [ ]:
output = mul(11,33)
output

363

In [ ]:
#
def num():
  return 50

In [ ]:
compare =num()

In [ ]:

if compare<90:
  print("excellent ,model")
else:
  print("again work on it")

excellent ,model

In [ ]:
import pandas as pd
df = pd.read_csv("/content/twitter_training.csv")
df.sample(5)

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
67183,7104,johnson&johnson,Negative,It's time to burn the phone lines with Congres...
2886,1701,CallOfDutyBlackopsColdWar,Positive,HOLYYY. Definitely streaming this weekend. Be ...
52736,10659,RedDeadRedemption(RDR),Irrelevant,And for good reason. It really is an amazing m...
42706,10126,PlayerUnknownsBattlegrounds(PUBG),Positive,But mobile is easier???. It might be too easy.
74088,9094,Nvidia,Positive,Yo. The NVIDIA show was crazy.

In [ ]:
# practice
def clean_data(data):
  cleaned = data.dropna()
  return cleaned

In [ ]:
clean_dataset =clean_data(df)
df.sample(3)

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
53668,2022,CallOfDuty,Neutral,I kinda gotta say not massive fan of anyone of...
34705,6761,Fortnite,Negative,didn't play for 5 minutes and 2 seconds youtu....
69209,3857,Cyberpunk2077,Negative,"Much to my disappointment, this article I wrot..."

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
def model_train(x,y):
  model= LinearRegression()
  model.fit(x,y)
  return model

In [ ]:
# LAMBDA FUNCTION
# normal dunction work
def addd(a,b):
  return a+b

In [ ]:
print(addd(10,290))

300

In [ ]:
# why use : Imagine you need a function only once.
# Instead of writing:function
# if we lambda
# this make code shoter
addd = lambda a,b: a+b

In [ ]:
addd(2222,24)

2246

In [ ]:
cube= lambda x:x*x*x
print(cube(5))

125

In [ ]:
avg =lambda x,y :x+y/2
print(avg(12,32))

28.0

In [ ]:
# map()
def cube(x):
  return x*x*x

In [ ]:
l=[1,2,3,4,5]

In [ ]:
result = list(map(cube,l))
result

[1, 8, 27, 64, 125]

In [ ]:
def sqr(x):
  return x*x

In [ ]:
list1=[1,2,3,4,5,6]

In [ ]:
new_l = list(map(sqr,list1))
new_l

[1, 4, 9, 16, 25, 36]

In [ ]:
# filter()
#  used to print only those values that qualify
def filter_item (a):
  return a>4

In [ ]:
new_list = list(filter(filter_item,list1))
new_list

[5, 6]

In [ ]:
# shorted()

File Handling

In [ ]:
file = open("/content/twitter_training.csv","r")

In [ ]:
content = file.read()

In [10]:
# insted of using python alone for file handling
# we use python with pandas
import pandas as pd
df =pd.read_csv("/content/twitter_training.csv")
df.head()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...

EXCEPTION HANDLING

In [ ]:
#  used if and error happens --do not crash --go to except block

# try --code that may cause and error

# except --code that runs if an error occurs

In [15]:
try:

   num = int (input("ENter a number : "))
   print(num)
except:
  print("ENter a valid number")

ENter a number : dwd
ENter a valid number

In [17]:
try:

   num1 = int (input("ENter a number : "))
   num2 = int (input("ENter a number : "))
   print(num1+num2)
except:
  print("something went wrong. f")

ENter a number : 33
ENter a number : f
something went wrong.

In [21]:
try:
   num1 = int (input("ENter a number : "))
   print(num1/0)
except ZeroDivisionError:
   print("cannot divid by zero")

ENter a number : 22
cannot divid by zero

In [22]:
try:
    age = int(input())

except ValueError:
    print("Please enter numbers only.")

ss
Please enter numbers only.

MODULES in python

In [ ]:
# python have modules that have some built in function
# math modules = used for mathematical calculation

In [ ]:
# import math

# math.sqrt()
# math.pow()
# math.factorial()

# math.ceil()
# math.floor()

# math.log()
# math.log10()
# math.exp()

# math.sin()
# math.cos()
# math.tan()

# math.pi
# math.e

In [23]:
import math
result = math.sqrt(25)
print(result)

5.0

In [25]:
result= math.pow(2,3)
print(result)

8.0

In [32]:
result= math.pow(12,21)
print(result)

4.60051199093697e+22

In [33]:
result= math.factorial(5)
print(result)

120

In [34]:
result= math.log(12)
print(result)

2.4849066497880004

In [ ]:
#  random

In [38]:
import random
num = random.randint(1,10)
print(num)

10

In [48]:
x =random.random()
print(x)

0.6883264425422098

In [50]:
# help to genrate  Integer value
x= random.randint(1,21)
print(x)

13

In [62]:
x =random.randrange(1,11,2)
x

1

In [65]:
# helps to genrate a decimal number
x= random.uniform(1,5)
x

1.4895380977257981

In [67]:
list1 =["tanvi",'laksahy','deepika','mona']
x= random.choice(list1)
x

'laksahy'

In [71]:
x =random.choices(list1 ,k =2)
x

['laksahy', 'tanvi']

In [80]:
lis=[1,2,3,3,4,5,6,7,8,9]

In [86]:
import random
random.shuffle(lis)
print(lis)

[3, 6, 2, 3, 4, 9, 8, 1, 5, 7]

In [92]:
random.sample(lis,3)

[3, 2, 9]

In [90]:
random.sample(lis,6)

[7, 1, 9, 2, 4, 6]

In [101]:
random.seed(10)
print(random.randint(1,1000))
#  it is same like a random_state in a machine learing to genrate a same output for all

586

# **PIP** python package installer

In [ ]:
# we use extra lib for work so we use pip to install them

In [102]:
pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [103]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [106]:
pip install matplotlib

Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [107]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [109]:
import matplotlib

In [110]:
import pandas as pd

# **Virtual** **Environment**

In [ ]:
# python -m venv myenv

In [ ]:
# myenv\Scripts\activate